version: '3.9'
services:
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
        volumes:
            - 'redisdata:/data'
        environment:
            - PUBLIC_URL=/ui
    redis-commander:
        image: rediscommander/redis-commander:latest
        environment:
            - REDIS_HOSTS=local:redis:6379
        ports:
            - '8081:8081'
    nestjs:
        build: .
        ports:
            - '3000:3000'
        links:
            - 'redis:redis'
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
    mkdocs:
        container_name: mkdocs
        image: polinux/mkdocs:latest
        restart: always
        ports:
            - '8000:8000'
        environment:
            - LIVE_RELOAD_SUPPORT=true
            - ADD_MODULES=fontawesome-markdown mkdocs-git-revision-date-localized-plugin mkdocs-material
            - FAST_MODE=true
            - DOCS_DIRECTORY=/mkdocs
            - UPDATE_INTERVAL=15
            - AUTO_UPDATE=true
        volumes:
            - ./docs:/docs
            - ./:/mkdocs
volumes:
    redisdata:
        driver: local
