apiVersion: apps/v1
kind: Deployment
metadata:
  name: dct
  namespace: dct
  labels:
    app: dct
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dct
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-init-first: 'true'
        vault.hashicorp.com/tls-secret: vault-tls-ca
        vault.hashicorp.com/ca-cert: '/vault/tls/tls.crt'
        vault.hashicorp.com/role: 'vault-dct'
        vault.hashicorp.com/agent-inject-secret-dct-app: 'dct/secret/app'
        vault.hashicorp.com/agent-inject-template-dct-app: |
          {{- with secret "dct/secret/app" -}}
          export REDIS_PASSWORD={{ .Data.redispass }}
          export SIGNATURE_PRIVATE_KEY_BASE58={{ .Data.sigprivkey }}
          {{- end -}}
      labels:
        app: dct
    spec:
      imagePullSecrets:
      - name: gitlab-access-token
      serviceAccountName: vault-dct
      containers:
      - name: dct
        image: registry.gitlab.com/gaia-x/data-infrastructure-federation-services/dct/dct:3ee4b875
        command: ["/bin/sh"]
        args: ["-c", "source /vault/secrets/dct-app && node dist/apps/api/main.js"]
        env:
        # general
        - name: NODE_ENV
          value: "production"
        # size in bytes
        - name: REQUEST_SIZE
          value: "1000000"

        # server
        - name: NX_API_ENDPOINT
          value: "http://localhost:3000/"
        - name: SERVER_THROTLLER_TTL
          value: "60"
        - name: SERVER_THROTLLER_LIMIT
          value: "10"

        #logger
        ## types "console"/"winston"
        - name: LOGGER_TYPE
          value: "console"
          
        - name: DEBUG
          value: "ioredis:*"
          
        # winston config
        - name: LOGGER_WINSTON_LEVEL
          value: "info"
        - name: LOGGER_WINSTON_TRANSPORTS_CONSOLE
          value: "true"
        - name: LOGGER_WINSTON_TRANSPORTS_FILE
          value: "logs/app.log"

        # cache
        ## types "memory"/"redis"
        - name: CACHE_TYPE
          value: "redis"
        - name: CACHE_TTL
          value: "86400"
        - name: TOKEN_TTL
          value: "86400"
        # 14 days in milliseconds
        - name: SD_CACHE_TTL
          value: "1209600000"
        # 24 hours in milliseconds
        - name: SD_QUEUE_DELAY
          value: "86400000"
        # QUEUE RETRIES
        - name: SD_QUEUE_RETRIES
          value: "13"
          
        ## redis config
        ## types node/cluster
        - name: REDIS_TYPE
          value: "cluster"
        - name: REDIS_HOST
          value: "dct-redis-cluster"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PREFIX
          value: "cache:"
        - name: DELS_LINK
          value: "https://del-dev3.gxfs.dev/inbox"
        - name: DELS_REL
          value: "http://www.w3.org/ns/ldp#inbox"
        - name: DELS_CONTEXT
          value: "http://www.w3.org/ns/ldp#inbox"
        #- name: DELS_CONTEXT
        #  value: "https://www.w3.org/ns/ldp"
        - name: DELS_ID
          value: "https://dcs.gaia-x.com/contracts/1001"
        - name: DELS_INBOX
          value: "https://del-dev3.gxfs.dev/inbox"

        #gateway
        - name: TRUST_SERVICE_URL
          value: "https://trust-service.com"
        - name: FEDERATED_CATALOG_URL
          value: "https://federated-catalog.com"

        - name: SIGNATURE_ID
          value: "did:dcs:key:123"
        - name: SIGNATURE_TYPE
          value: "Ed25519VerificationKey2018"
        - name: SIGNATURE_CONTROLLER
          value: "did:dcs:controller"
        - name: SIGNATURE_PUBLIC_KEY_BASE58
          value: "45dxsXGjMixWNfmXBtWwPnCfGgV1THf6qhdLixUmgrVZ"

        - name: LOG_TOKEN_JWT_SECRET_KEY
          value: "somesecretkey"
        - name: LOG_TOKEN_EXPIRES_IN_MINUTES
          value: "120"

        #health-check
        - name: API_DOCUMENTATION_URL
          value: "http://localhost:8000/"
        ports:
        - name: http
          containerPort: 3000
