apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mkdocs-claim0
  name: mkdocs-claim0
  namespace: dct
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi